%PAKCS1.10 sicstus4 VARIABLESHARING

:-noSingletonWarnings.
:-noRedefineWarnings.
:-noDiscontiguousWarnings.

:-importModule('CurryDocParams').
:-importModule('CurryDocRead').
:-importModule('FlatCurry').
:-importModule('HTML').
:-importModule('HtmlParser').
:-importModule('List').
:-importModule('Markdown').
:-importModule('Prelude').


:-curryModule('CurryDocTeX').

%%%%%%%%%%%% function types %%%%%%%%%%%%%%%%%%%
:-multifile functiontype/6.
:-dynamic functiontype/6.
functiontype('CurryDocTeX.generateTexDocs',generateTexDocs,5,'CurryDocTeX.generateTexDocs',nofix,'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'('CurryDocRead.AnaInfo',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'FuncType'('TCons'([],['TCons'('Prelude.(,)',['TCons'('CurryDocRead.SourceLine',[]),'TCons'([],['TCons'('Prelude.Char',[])])])]),'TCons'('Prelude.IO',['TCons'('Prelude.(,)',['TCons'([],['TCons'([],['TCons'('Prelude.Char',[])])]),'TCons'([],['TCons'('Prelude.Char',[])])])]))))))).
functiontype('CurryDocTeX.generateTexDocs\'2E_\'23lambda1','CurryDocTeX.generateTexDocs._#lambda1',6,'CurryDocTeX.generateTexDocs\'2E_\'23lambda1',nofix,'FuncType'('TCons'('CurryDocRead.AnaInfo',[]),'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'FuncType'('TCons'([],['TCons'('Prelude.(,)',['TCons'('CurryDocRead.SourceLine',[]),'TCons'([],['TCons'('Prelude.Char',[])])])]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'FuncType'('TCons'('FlatCurry.Prog',[]),'TCons'('Prelude.IO',['TCons'('Prelude.(,)',['TCons'([],['TCons'([],['TCons'('Prelude.Char',[])])]),'TCons'([],['TCons'('Prelude.Char',[])])])])))))))).
functiontype('CurryDocTeX.htmlString2Tex',htmlString2Tex,2,'CurryDocTeX.htmlString2Tex',nofix,'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])))).
functiontype('CurryDocTeX.genTexFunc',genTexFunc,4,'CurryDocTeX.genTexFunc',nofix,'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'([],['TCons'('Prelude.(,)',['TCons'('CurryDocRead.SourceLine',[]),'TCons'([],['TCons'('Prelude.Char',[])])])]),'FuncType'(A,'FuncType'('TCons'('FlatCurry.FuncDecl',[]),'TCons'([],['TCons'('Prelude.Char',[])])))))).
functiontype('CurryDocTeX.genTexType',genTexType,3,'CurryDocTeX.genTexType',nofix,'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'([],['TCons'('Prelude.(,)',['TCons'('CurryDocRead.SourceLine',[]),'TCons'([],['TCons'('Prelude.Char',[])])])]),'FuncType'('TCons'('FlatCurry.TypeDecl',[]),'TCons'([],['TCons'('Prelude.Char',[])]))))).
functiontype('CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22','CurryDocTeX.genTexType.genHtmlCons.22',5,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22',nofix,'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'FuncType'('TCons'([],['TCons'('Prelude.Int',[])]),'FuncType'('TCons'([],['TCons'([],['TCons'('Prelude.Char',[])])]),'FuncType'('TCons'('FlatCurry.ConsDecl',[]),'TCons'([],['TCons'('Prelude.Char',[])]))))))).
functiontype('CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda2','CurryDocTeX.genTexType.genHtmlCons.22._#lambda2',1,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda2',nofix,'FuncType'('TCons'('FlatCurry.TypeExpr',[]),'TCons'([],['TCons'('Prelude.Char',[])]))).
functiontype('CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda3','CurryDocTeX.genTexType.genHtmlCons.22._#lambda3',1,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda3',nofix,'FuncType'('TCons'('Prelude.Int',[]),'TCons'([],['TCons'('Prelude.Char',[])]))).
functiontype('CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4','CurryDocTeX.genTexType.genHtmlCons.22._#lambda4',2,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4',nofix,'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])]),'TCons'([],['TCons'('Prelude.Char',[])])))).
functiontype('CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt','CurryDocTeX.genTexType._#selFP2#datacmt',1,'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt',nofix,'FuncType'('TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])])])]),'TCons'([],['TCons'('Prelude.Char',[])]))).
functiontype('CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts','CurryDocTeX.genTexType._#selFP3#conscmts',1,'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts',nofix,'FuncType'('TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])])])]),'TCons'([],['TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])])]))).
functiontype('CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt','CurryDocTeX.genTexType._#selFP5#typecmt',1,'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt',nofix,'FuncType'('TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.(,)',['TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])])])]),'TCons'([],['TCons'('Prelude.Char',[])]))).
functiontype('CurryDocTeX.genTexType\'2E_\'23lambda5','CurryDocTeX.genTexType._#lambda5',1,'CurryDocTeX.genTexType\'2E_\'23lambda5',nofix,'FuncType'('TCons'('Prelude.Int',[]),'TCons'([],['TCons'('Prelude.Char',[])]))).
functiontype('CurryDocTeX.showTexType',showTexType,2,'CurryDocTeX.showTexType',nofix,'FuncType'('TCons'('Prelude.Bool',[]),'FuncType'('TCons'('FlatCurry.TypeExpr',[]),'TCons'([],['TCons'('Prelude.Char',[])])))).
functiontype('CurryDocTeX.string2tex',string2tex,0,'CurryDocTeX.string2tex',nofix,'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])]))).
functiontype('CurryDocTeX.string2tex\'2Echar2tex\'2E50','CurryDocTeX.string2tex.char2tex.50',1,'CurryDocTeX.string2tex\'2Echar2tex\'2E50',nofix,'FuncType'('TCons'('Prelude.Char',[]),'TCons'([],['TCons'('Prelude.Char',[])]))).
functiontype('CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0','CurryDocTeX.generateTexDocs._#lambda1._#caseor0',3,'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0',nofix,'FuncType'('TCons'('Prelude.Bool',[]),'FuncType'('TCons'('CurryDocParams.DocParams',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])]))))).
functiontype('CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0','CurryDocTeX.generateTexDocs._#lambda1._#caseor0._#caseor0',2,'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0',nofix,'FuncType'('TCons'('Prelude.Bool',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])))).
functiontype('CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0','CurryDocTeX.generateTexDocs._#lambda1._#caseor0._#caseor0._#caseor0',2,'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0',nofix,'FuncType'('TCons'('Prelude.Bool',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'TCons'([],['TCons'('Prelude.Char',[])])))).
functiontype('CurryDocTeX.genTexType\'2E_\'23caseor0','CurryDocTeX.genTexType._#caseor0',4,'CurryDocTeX.genTexType\'2E_\'23caseor0',nofix,'FuncType'('TCons'('Prelude.Bool',[]),'FuncType'('TCons'([],['TCons'('Prelude.Char',[])]),'FuncType'('TCons'([],['TCons'('Prelude.Int',[])]),'FuncType'('TCons'('FlatCurry.TypeExpr',[]),'TCons'([],['TCons'('Prelude.Char',[])])))))).

%%%%%%%%%%%% constructor types %%%%%%%%%%%%%%%%%%%
:-multifile constructortype/6.
:-dynamic constructortype/6.

%%%%%%%%%%%% function definitions %%%%%%%%%%%%%%%%%%%
:-block 'CurryDocTeX.generateTexDocs'(?,?,?,?,?,?,-,?).
'CurryDocTeX.generateTexDocs'(A,B,C,D,E,F,G,H):-makeShare(I,J),makeShare(C,K),hnf('Prelude.cond'('Prelude.letrec'(J,'FlatCurry.flatCurryFileName'(K)),'Prelude.>>'('Prelude.$'(partcall(1,'Prelude.putStrLn',[]),'Prelude.++'(['^R','^e','^a','^d','^i','^n','^g','^ ','^F','^l','^a','^t','^C','^u','^r','^r','^y','^ ','^p','^r','^o','^g','^r','^a','^m','^ ','^"'],'Prelude.++'(J,['^"',^.,^.,^.]))),'Prelude.>>='('FlatCurry.readFlatCurryFile'(J),partcall(1,'CurryDocTeX.generateTexDocs\'2E_\'23lambda1',[K,E,D,A,B])))),F,G,H).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1'(?,?,?,?,?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1'(A,B,C,D,E,F,G,H,I):-hnf(F,J,H,K),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1_6'(J,A,B,C,D,E,G,K,I).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1_6'(?,?,?,?,?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1_6'('FlatCurry.Prog'(A,B,C,D,E),F,G,H,I,J,K,L,M):-!,makeShare(N,O),makeShare(G,P),makeShare(I,Q),makeShare(R,S),makeShare(T,U),hnf('Prelude.cond'('Prelude.letrec'(O,'Prelude.apply'('Prelude.concatMap'(partcall(1,'CurryDocTeX.genTexType',[Q,P])),C)),'Prelude.cond'('Prelude.letrec'(S,'Prelude.apply'('Prelude.concatMap'(partcall(1,'CurryDocTeX.genTexFunc',[F,Q,P])),D)),'Prelude.cond'('Prelude.letrec'(U,'Prelude.fst'('CurryDocRead.splitComment'(H))),'Prelude.$'(partcall(1,'Prelude.return',[]),'Prelude.(,)'(B,'Prelude.++'([^\,'^c','^u','^r','^r','^y','^m','^o','^d','^u','^l','^e','^{'],'Prelude.++'('Prelude.apply'('CurryDocRead.getLastName',J),'Prelude.++'(['^}','^010'],'Prelude.++'('CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0'('CurryDocParams.withMarkdown'(P),P,U),'Prelude.++'(['^010'],'Prelude.++'('CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0'('Prelude.null'(O),O),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0'('Prelude.null'(S),S)))))))))))),K,L,M).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1_6'('FAIL'(A),B,C,D,E,F,'FAIL'(A),G,G):-nonvar(A).

:-block 'CurryDocTeX.htmlString2Tex'(?,?,?,-,?).
'CurryDocTeX.htmlString2Tex'(A,B,C,D,E):-hnf('CurryDocParams.withMarkdown'(A),F,D,G),'CurryDocTeX.htmlString2Tex_ComplexCase'(F,A,B,C,G,E).

:-block 'CurryDocTeX.htmlString2Tex_ComplexCase'(-,?,?,?,?,?),'CurryDocTeX.htmlString2Tex_ComplexCase'(?,?,?,?,-,?).
'CurryDocTeX.htmlString2Tex_ComplexCase'('Prelude.True',A,B,C,D,E):-hnf('Prelude.apply'('Markdown.markdownText2LaTeX',B),C,D,E).
'CurryDocTeX.htmlString2Tex_ComplexCase'('Prelude.False',A,B,C,D,E):-!,hnf('HTML.showLatexExps'('HtmlParser.parseHtmlString'(B)),C,D,E).
'CurryDocTeX.htmlString2Tex_ComplexCase'('FAIL'(A),B,C,'FAIL'(A),D,D).

:-block 'CurryDocTeX.genTexFunc'(?,?,?,?,?,-,?).
'CurryDocTeX.genTexFunc'(A,B,C,D,E,F,G):-hnf(D,H,F,I),'CurryDocTeX.genTexFunc_4'(H,A,B,C,E,I,G).

:-block 'CurryDocTeX.genTexFunc_4'(?,?,?,?,?,-,?).
'CurryDocTeX.genTexFunc_4'('FlatCurry.Func'(A,B,C,D,E),F,G,H,I,J,K):-!,hnf(A,L,J,M),'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1'(L,B,C,D,E,F,G,H,I,M,K).

:-block 'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1'(?,?,?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1'('Prelude.(,)'(A,B),C,D,E,F,G,H,I,J,K,L):-!,hnf('Prelude.=='(D,'FlatCurry.Public'),M,K,N),'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1_Prelude.(,)_ComplexCase'(M,A,B,C,D,E,F,G,H,I,J,N,L).

:-block 'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1_Prelude.(,)_ComplexCase'(-,?,?,?,?,?,?,?,?,?,?,?,?),'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1_Prelude.(,)_ComplexCase'(?,?,?,?,?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1_Prelude.(,)_ComplexCase'('Prelude.True',A,B,C,D,E,F,G,H,I,J,K,L):-makeShare(B,M),hnf('Prelude.++'([^\,'^c','^u','^r','^r','^y','^f','^u','^n','^c','^t','^i','^o','^n','^s','^t','^a','^r','^t','^{'],'Prelude.++'('Prelude.apply'('CurryDocTeX.string2tex',M),'Prelude.++'(['^}','^{'],'Prelude.++'([^\,'^c','^u','^r','^r','^y','^f','^u','^n','^c','^s','^i','^g','^{'],'Prelude.++'('Prelude.apply'('CurryDocTeX.string2tex','CurryDocRead.showId'(M)),'Prelude.++'(['^}','^{'],'Prelude.++'('CurryDocTeX.showTexType'('Prelude.False',E),'Prelude.++'(['^}','^}','^010'],'Prelude.++'('CurryDocTeX.htmlString2Tex'(G,'Prelude.fst'('CurryDocRead.splitComment'('CurryDocRead.getFuncComment'(M,H)))),[^\,'^c','^u','^r','^r','^y','^f','^u','^n','^c','^t','^i','^o','^n','^s','^t','^o','^p','^010']))))))))),J,K,L).
'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1_Prelude.(,)_ComplexCase'('Prelude.False',A,B,C,D,E,F,G,H,I,[],J,J):-!.
'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1_Prelude.(,)_ComplexCase'('FAIL'(A),B,C,D,E,F,G,H,I,J,'FAIL'(A),K,K).
'CurryDocTeX.genTexFunc_4_FlatCurry.Func_1'('FAIL'(A),B,C,D,E,F,G,H,'FAIL'(A),I,I):-nonvar(A).
'CurryDocTeX.genTexFunc_4'('FAIL'(A),B,C,D,'FAIL'(A),E,E):-nonvar(A).

:-block 'CurryDocTeX.genTexType'(?,?,?,?,-,?).
'CurryDocTeX.genTexType'(A,B,C,D,E,F):-hnf(C,G,E,H),'CurryDocTeX.genTexType_3'(G,A,B,D,H,F).

:-block 'CurryDocTeX.genTexType_3'(?,?,?,?,-,?).
'CurryDocTeX.genTexType_3'('FlatCurry.Type'(A,B,C,D),E,F,G,H,I):-hnf(A,J,H,K),'CurryDocTeX.genTexType_3_FlatCurry.Type_1'(J,B,C,D,E,F,G,K,I).

:-block 'CurryDocTeX.genTexType_3_FlatCurry.Type_1'(?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType_3_FlatCurry.Type_1'('Prelude.(,)'(A,B),C,D,E,F,G,H,I,J):-!,hnf('Prelude.=='(C,'FlatCurry.Public'),K,I,L),'CurryDocTeX.genTexType_3_FlatCurry.Type_1_Prelude.(,)_ComplexCase'(K,A,B,C,D,E,F,G,H,L,J).

:-block 'CurryDocTeX.genTexType_3_FlatCurry.Type_1_Prelude.(,)_ComplexCase'(-,?,?,?,?,?,?,?,?,?,?),'CurryDocTeX.genTexType_3_FlatCurry.Type_1_Prelude.(,)_ComplexCase'(?,?,?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType_3_FlatCurry.Type_1_Prelude.(,)_ComplexCase'('Prelude.True',A,B,C,D,E,F,G,H,I,J):-makeShare(K,L),makeShare(B,M),makeShare(N,O),makeShare(P,Q),makeShare(F,R),hnf('Prelude.cond'('Prelude.letrec'(L,'CurryDocRead.splitComment'('CurryDocRead.getDataComment'(M,G))),'Prelude.cond'('Prelude.letrec'(O,'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt'(L)),'Prelude.cond'('Prelude.letrec'(Q,'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts'(L)),'Prelude.++'([^\,'^c','^u','^r','^r','^y','^d','^a','^t','^a','^s','^t','^a','^r','^t','^{'],'Prelude.++'(M,'Prelude.++'(['^}','^010'],'Prelude.++'('CurryDocTeX.htmlString2Tex'(R,O),'Prelude.++'(['^010',^\,'^c','^u','^r','^r','^y','^d','^a','^t','^a','^c','^o','^n','^s','^010'],'Prelude.++'('Prelude.apply'('Prelude.concatMap'(partcall(1,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22',['CurryDocRead.getCommentType'(['^c','^o','^n','^s'],Q),D,M,R])),E),[^\,'^c','^u','^r','^r','^y','^d','^a','^t','^a','^s','^t','^o','^p','^010']))))))))),H,I,J).
'CurryDocTeX.genTexType_3_FlatCurry.Type_1_Prelude.(,)_ComplexCase'('Prelude.False',A,B,C,D,E,F,G,[],H,H):-!.
'CurryDocTeX.genTexType_3_FlatCurry.Type_1_Prelude.(,)_ComplexCase'('FAIL'(A),B,C,D,E,F,G,H,'FAIL'(A),I,I).
'CurryDocTeX.genTexType_3_FlatCurry.Type_1'('FAIL'(A),B,C,D,E,F,'FAIL'(A),G,G):-nonvar(A).
'CurryDocTeX.genTexType_3'('FlatCurry.TypeSyn'(A,B,C,D),E,F,G,H,I):-!,hnf(A,J,H,K),'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1'(J,B,C,D,E,F,G,K,I).

:-block 'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1'(?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1'('Prelude.(,)'(A,B),C,D,E,F,G,H,I,J):-!,hnf('Prelude.=='(C,'FlatCurry.Public'),K,I,L),'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1_Prelude.(,)_ComplexCase'(K,A,B,C,D,E,F,G,H,L,J).

:-block 'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1_Prelude.(,)_ComplexCase'(-,?,?,?,?,?,?,?,?,?,?),'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1_Prelude.(,)_ComplexCase'(?,?,?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1_Prelude.(,)_ComplexCase'('Prelude.True',A,B,C,D,E,F,G,H,I,J):-makeShare(K,L),makeShare(B,M),makeShare(N,O),hnf('Prelude.cond'('Prelude.letrec'(L,'CurryDocRead.splitComment'('CurryDocRead.getDataComment'(M,G))),'Prelude.cond'('Prelude.letrec'(O,'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt'(L)),'Prelude.++'([^\,'^c','^u','^r','^r','^y','^t','^y','^p','^e','^s','^y','^n','^s','^t','^a','^r','^t','^{'],'Prelude.++'(M,'Prelude.++'(['^}','^{'],'Prelude.++'('CurryDocTeX.genTexType\'2E_\'23caseor0'('Prelude.&&'('Prelude.=='(M,['^S','^t','^r','^i','^n','^g']),'Prelude.=='(A,['^P','^r','^e','^l','^u','^d','^e'])),M,D,E),'Prelude.++'(['^}','^010'],'Prelude.++'('CurryDocTeX.htmlString2Tex'(F,O),[^\,'^c','^u','^r','^r','^y','^t','^y','^p','^e','^s','^y','^n','^s','^t','^o','^p','^010','^010'])))))))),H,I,J).
'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1_Prelude.(,)_ComplexCase'('Prelude.False',A,B,C,D,E,F,G,[],H,H):-!.
'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1_Prelude.(,)_ComplexCase'('FAIL'(A),B,C,D,E,F,G,H,'FAIL'(A),I,I).
'CurryDocTeX.genTexType_3_FlatCurry.TypeSyn_1'('FAIL'(A),B,C,D,E,F,'FAIL'(A),G,G):-nonvar(A).
'CurryDocTeX.genTexType_3'('FAIL'(A),B,C,'FAIL'(A),D,D):-nonvar(A).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22'(?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22'(A,B,C,D,E,F,G,H):-hnf(E,I,G,J),'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5'(I,A,B,C,D,F,J,H).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5'(?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5'('FlatCurry.Cons'(A,B,C,D),E,F,G,H,I,J,K):-!,hnf(A,L,J,M),'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1'(L,B,C,D,E,F,G,H,I,M,K).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1'(?,?,?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1'('Prelude.(,)'(A,B),C,D,E,F,G,H,I,J,K,L):-!,hnf('Prelude.=='(D,'FlatCurry.Public'),M,K,N),'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1_Prelude.(,)_ComplexCase'(M,A,B,C,D,E,F,G,H,I,J,N,L).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1_Prelude.(,)_ComplexCase'(-,?,?,?,?,?,?,?,?,?,?,?,?),'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1_Prelude.(,)_ComplexCase'(?,?,?,?,?,?,?,?,?,?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1_Prelude.(,)_ComplexCase'('Prelude.True',A,B,C,D,E,F,G,H,I,J,K,L):-makeShare(B,M),hnf('Prelude.++'([^\,'^c','^u','^r','^r','^y','^c','^o','^n','^s','^s','^t','^a','^r','^t','^{'],'Prelude.++'(M,'Prelude.++'(['^}','^{'],'Prelude.++'('Prelude.apply'('Prelude.concatMap'(partcall(1,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda2',[])),E),'Prelude.++'(G,'Prelude.++'('Prelude.apply'('Prelude.concatMap'(partcall(1,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda3',[])),H),'Prelude.++'(['^}','^010'],'Prelude.++'('Prelude.maybe'([],partcall(1,'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4',[F]),'CurryDocRead.getConsComment'(I,M)),['^010'])))))))),J,K,L).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1_Prelude.(,)_ComplexCase'('Prelude.False',A,B,C,D,E,F,G,H,I,[],J,J):-!.
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1_Prelude.(,)_ComplexCase'('FAIL'(A),B,C,D,E,F,G,H,I,J,'FAIL'(A),K,K).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5_FlatCurry.Cons_1'('FAIL'(A),B,C,D,E,F,G,H,'FAIL'(A),I,I):-nonvar(A).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22_5'('FAIL'(A),B,C,D,E,'FAIL'(A),F,F):-nonvar(A).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda2'(?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda2'(A,B,C,D):-hnf('Prelude.++'('CurryDocTeX.showTexType'('Prelude.True',A),['^ ',^$,^\,'^t','^o',^$,'^ ']),B,C,D).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda3'(?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda3'(A,['^ ','Prelude.chr'('Prelude.+'(97,A))],B,B).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4'(?,?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4'(A,B,C,D,E):-hnf(B,F,D,G),'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4_2'(F,A,C,G,E).

:-block 'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4_2'(?,?,?,-,?).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4_2'('Prelude.(,)'(A,B),C,D,E,F):-!,hnf('Prelude.++'(['^{',^\,'^t','^t','^ '],'Prelude.++'(A,'Prelude.++'(['^}'],'CurryDocTeX.htmlString2Tex'(C,B)))),D,E,F).
'CurryDocTeX.genTexType\'2EgenHtmlCons\'2E22\'2E_\'23lambda4_2'('FAIL'(A),B,'FAIL'(A),C,C):-nonvar(A).

:-block 'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt'(?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt'(A,B,C,D):-hnf(A,E,C,F),'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt_1'(E,B,F,D).

:-block 'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt_1'(?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt_1'('Prelude.(,)'(A,B),C,D,E):-!,hnf(A,C,D,E).
'CurryDocTeX.genTexType\'2E_\'23selFP2\'23datacmt_1'('FAIL'(A),'FAIL'(A),B,B):-nonvar(A).

:-block 'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts'(?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts'(A,B,C,D):-hnf(A,E,C,F),'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts_1'(E,B,F,D).

:-block 'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts_1'(?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts_1'('Prelude.(,)'(A,B),C,D,E):-!,hnf(B,C,D,E).
'CurryDocTeX.genTexType\'2E_\'23selFP3\'23conscmts_1'('FAIL'(A),'FAIL'(A),B,B):-nonvar(A).

:-block 'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt'(?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt'(A,B,C,D):-hnf(A,E,C,F),'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt_1'(E,B,F,D).

:-block 'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt_1'(?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt_1'('Prelude.(,)'(A,B),C,D,E):-!,hnf(A,C,D,E).
'CurryDocTeX.genTexType\'2E_\'23selFP5\'23typecmt_1'('FAIL'(A),'FAIL'(A),B,B):-nonvar(A).

:-block 'CurryDocTeX.genTexType\'2E_\'23lambda5'(?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23lambda5'(A,['^ ','Prelude.chr'('Prelude.+'(97,A))],B,B).

:-block 'CurryDocTeX.showTexType'(?,?,?,-,?).
'CurryDocTeX.showTexType'(A,B,C,D,E):-hnf(B,F,D,G),'CurryDocTeX.showTexType_2'(F,A,C,G,E).

:-block 'CurryDocTeX.showTexType_2'(?,?,?,-,?).
'CurryDocTeX.showTexType_2'('FlatCurry.TVar'(A),B,['Prelude.chr'('Prelude.+'(97,A))],C,C).
'CurryDocTeX.showTexType_2'('FlatCurry.FuncType'(A,B),C,D,E,F):-makeShare(A,G),hnf('CurryDocRead.brackets'(C,'Prelude.++'('CurryDocTeX.showTexType'('CurryDocRead.isFunctionType'(G),G),'Prelude.++'(['^ ',^$,^\,'^t','^o',^$,'^ '],'CurryDocTeX.showTexType'('Prelude.False',B)))),D,E,F).
'CurryDocTeX.showTexType_2'('FlatCurry.TCons'(A,B),C,D,E,F):-!,makeShare(B,G),hnf('Prelude.=='(G,[]),H,E,I),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase'(H,A,G,C,D,I,F).

:-block 'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase'(-,?,?,?,?,?,?),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase'(?,?,?,?,?,-,?).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase'('Prelude.True',A,B,C,D,E,F):-hnf('Prelude.snd'(A),D,E,F).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase'('Prelude.False',A,B,C,D,E,F):-!,makeShare(A,G),makeShare(B,H),hnf('Prelude.&&'('Prelude.=='(G,'Prelude.(,)'(['^P','^r','^e','^l','^u','^d','^e'],['^[','^]'])),'Prelude.=='('Prelude.head'(H),'FlatCurry.TCons'('Prelude.(,)'(['^P','^r','^e','^l','^u','^d','^e'],['^C','^h','^a','^r']),[]))),I,E,J),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase'(I,G,H,C,D,J,F).

:-block 'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?,?,?),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase'(?,?,?,?,?,-,?).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,B,C,['^S','^t','^r','^i','^n','^g'],D,D).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D,E,F):-!,makeShare(A,G),hnf('Prelude.=='(G,'Prelude.(,)'(['^P','^r','^e','^l','^u','^d','^e'],['^[','^]'])),H,E,I),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(H,G,B,C,D,I,F).

:-block 'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?,?,?),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,?,?,-,?).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,B,C,D,E,F):-hnf('Prelude.++'(['^['],'Prelude.++'('CurryDocTeX.showTexType'('Prelude.False','Prelude.head'(B)),['^]'])),D,E,F).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D,E,F):-!,makeShare(A,G),hnf('Prelude.=='('Prelude.take'(2,'Prelude.snd'(G)),['^(','^,']),H,E,I),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(H,G,B,C,D,I,F).

:-block 'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?,?,?),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,?,?,-,?).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,B,C,D,E,F):-hnf('Prelude.++'(['^('],'Prelude.++'('Prelude.concat'('List.intersperse'(['^,'],'Prelude.map'(partcall(1,'CurryDocTeX.showTexType',['Prelude.False']),B))),['^)'])),D,E,F).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D,E,F):-!,hnf('Prelude.otherwise',G,E,H),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(G,A,B,C,D,H,F).

:-block 'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?,?,?),'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,?,?,-,?).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,B,C,D,E,F):-hnf('CurryDocRead.brackets'(C,'Prelude.++'('Prelude.snd'(A),'Prelude.++'(['^ '],'Prelude.concat'('List.intersperse'(['^ '],'Prelude.map'(partcall(1,'CurryDocTeX.showTexType',['Prelude.True']),B)))))),D,E,F).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D,E,F):-!,hnf('Prelude.failure'('CurryDocTeX.showTexType',['Prelude.False']),D,E,F).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,C,D,'FAIL'(A),E,E).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,C,D,'FAIL'(A),E,E).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,C,D,'FAIL'(A),E,E).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,C,D,'FAIL'(A),E,E).
'CurryDocTeX.showTexType_2_FlatCurry.TCons_ComplexCase'('FAIL'(A),B,C,D,'FAIL'(A),E,E).
'CurryDocTeX.showTexType_2'('FAIL'(A),B,'FAIL'(A),C,C):-nonvar(A).

:-block 'CurryDocTeX.string2tex'(?,-,?).
'CurryDocTeX.string2tex'(A,B,C):-hnf('Prelude.concatMap'(partcall(1,'CurryDocTeX.string2tex\'2Echar2tex\'2E50',[])),A,B,C).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50'(?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50'(A,B,C,D):-makeShare(A,E),hnf('Prelude.=='(E,'Prelude.chr'(228)),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase'('Prelude.True',A,[^\,'^"','^a'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'Prelude.chr'(246)),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^"','^o'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'Prelude.chr'(252)),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^"','^u'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'Prelude.chr'(196)),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^"','^A'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'Prelude.chr'(214)),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^"','^O'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'Prelude.chr'(220)),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^"','^U'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'Prelude.chr'(223)),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^s','^s','^{','^}'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,^~),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,['^{',^\,'^c','^h','^a','^r','^1','^2','^6','^}'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,^\),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,['^{',^\,'^c','^h','^a','^r','^9','^2','^}'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,^<),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,['^{',^$,^<,^$,'^}'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,^>),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,['^{',^$,^>,^$,'^}'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'^_'),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^_'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,^#),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,^#],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,^$),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,^$],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'^%'),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^%'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'^{'),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^{'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,'^}'),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,'^}'],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,makeShare(A,E),hnf('Prelude.=='(E,^&),F,C,G),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(F,E,B,G,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[^\,^&],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,hnf('Prelude.otherwise',E,C,F),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(E,A,B,F,D).

:-block 'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(-,?,?,?,?),'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'(?,?,?,-,?).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.True',A,[A],B,B).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('Prelude.False',A,B,C,D):-!,hnf('Prelude.failure'('CurryDocTeX.string2tex\'2Echar2tex\'2E50',['Prelude.False']),B,C,D).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase_Prelude.False_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).
'CurryDocTeX.string2tex\'2Echar2tex\'2E50_ComplexCase'('FAIL'(A),B,'FAIL'(A),C,C).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0'(?,?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0'(A,B,C,D,E,F):-hnf(A,G,E,H),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0_1'(G,B,C,D,H,F).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0_1'(-,?,?,?,?,?),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0_1'(?,?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0_1'('Prelude.True',A,B,C,D,E):-hnf('Prelude.apply'('Markdown.markdownText2LaTeX',B),C,D,E).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0_1'('Prelude.False',A,B,C,D,E):-!,hnf('CurryDocTeX.htmlString2Tex'(A,B),C,D,E).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0_1'('FAIL'(A),B,C,'FAIL'(A),D,D).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0'(?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0'(A,B,C,D,E):-hnf(A,F,D,G),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0_1'(F,B,C,G,E).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0_1'(-,?,?,?,?),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0_1'(?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0_1'('Prelude.True',A,[],B,B).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0_1'('Prelude.False',A,B,C,D):-!,hnf('Prelude.++'([^\,'^c','^u','^r','^r','^y','^t','^y','^p','^e','^s','^s','^t','^a','^r','^t','^010'],'Prelude.++'(A,[^\,'^c','^u','^r','^r','^y','^t','^y','^p','^e','^s','^s','^t','^o','^p','^010'])),B,C,D).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0_1'('FAIL'(A),B,'FAIL'(A),C,C).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0'(?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0'(A,B,C,D,E):-hnf(A,F,D,G),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0_1'(F,B,C,G,E).

:-block 'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0_1'(-,?,?,?,?),'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0_1'(?,?,?,-,?).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0_1'('Prelude.True',A,[],B,B).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0_1'('Prelude.False',A,B,C,D):-!,hnf('Prelude.++'([^\,'^c','^u','^r','^r','^y','^f','^u','^n','^c','^s','^t','^a','^r','^t','^010'],'Prelude.++'(A,[^\,'^c','^u','^r','^r','^y','^f','^u','^n','^c','^s','^t','^o','^p','^010'])),B,C,D).
'CurryDocTeX.generateTexDocs\'2E_\'23lambda1\'2E_\'23caseor0\'2E_\'23caseor0\'2E_\'23caseor0_1'('FAIL'(A),B,'FAIL'(A),C,C).

:-block 'CurryDocTeX.genTexType\'2E_\'23caseor0'(?,?,?,?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23caseor0'(A,B,C,D,E,F,G):-hnf(A,H,F,I),'CurryDocTeX.genTexType\'2E_\'23caseor0_1'(H,B,C,D,E,I,G).

:-block 'CurryDocTeX.genTexType\'2E_\'23caseor0_1'(-,?,?,?,?,?,?),'CurryDocTeX.genTexType\'2E_\'23caseor0_1'(?,?,?,?,?,-,?).
'CurryDocTeX.genTexType\'2E_\'23caseor0_1'('Prelude.True',A,B,C,['^S','^t','^r','^i','^n','^g','^ ',^=,'^ ','^[','^C','^h','^a','^r','^]'],D,D).
'CurryDocTeX.genTexType\'2E_\'23caseor0_1'('Prelude.False',A,B,C,D,E,F):-!,hnf('Prelude.++'(A,'Prelude.++'('Prelude.apply'('Prelude.concatMap'(partcall(1,'CurryDocTeX.genTexType\'2E_\'23lambda5',[])),B),'Prelude.++'(['^ ',^=,'^ '],'CurryDocTeX.showTexType'('Prelude.False',C)))),D,E,F).
'CurryDocTeX.genTexType\'2E_\'23caseor0_1'('FAIL'(A),B,C,D,'FAIL'(A),E,E).

:-costCenters(['']).




%%%%% Number of shared variables: 41
